l = [5, 7, 2, 9, 4, 1, 3]
print("Lista")
print(l)
print()
print("a) tamanho da lista")
print(len(l))
print()
print("b) mario valor da lista")
print(max(l))
print()
print("c) menor valor da lista")
print(min(l))
print()
print("d) soma de todos os elementos da lista")
print(sum(l))
print()
print("e) lista em ordem crescente")
print(sorted(l))
print()
print("f) lista em ordem decrescente")
print(sorted(l, reverse=True))
print()